### PR TITLE
Complete refactor without changing API: Rewrite in TS, use Jest, update benchmarks

### PR DESCRIPTION
**Pull request by hossam-magdy**
**While keeping the API unchanged for the package consumers, the following changes are introduced:**
- [x] rewrite the whole codebase in TypeScipt
- [x] use Jest with TS (instead of mocha+should+nyc)
- [x] configure `eslint`+`prettier` + TS parser
- [x] update `travis.yml` to use [defaults](https://docs.travis-ci.com/user/languages/javascript-with-nodejs/) and node 12
- [x] apply strict typing: `tsconfig.noImplicitAny: true`
- [x] write benchmarking shell script (`./bench/_bench.sh`)
- [x] update benchmark results (in README)
- [x] check solvable issues => solved #22 and wrote test for it
- [x] ensure all pre-written tests are passing
- [x] ensure the success of `yarn build`, generated `dist/` and `npm pack/publish`
- [x] add `.vscode/launch.json` ready-config for debugging tests
- [x] configure easily-accessible scripts: `yarn build`, `yarn lint`, `yarn test`, `yarn bench`

**Noticed possible further improvements… for later**
- change the API so that functions accept `options: object`, instead of multi-signature/overriding functions (major release, breaking change)
- fix the opposite case of issue #22 `stringify(parse(STRING_OF_ISSUE22))`. A test for it is already added in this PR and skipped

### CODE REVIEW

**Comment by touv** [comment]
wahou, very big job !!
I need some time to tests with our production product.
I 'll give you a feedback as soon as possible.

**Comment by touv** [comment]
@hossam-magdy Can I merge  this PR ?

**Comment by hossam-magdy** [comment]
Even though you already did 🎉 , Yes! 😄

**Comment by hossam-magdy** [comment]
@touv Even though you already did 🎉 , Yes! 😄

**Comment by touv** [comment]
😋
thanks for your job !

**Pull request merged**
